=== lee0nerd0/XML-DTD/owner.dtd
<!ELEMENT Owner (Indiv|Corp)*>

<!ELEMENT Indiv (Name, Addr, Phone+)>
<!ATTLIST Indiv Id CDATA #REQUIRED>
<!ELEMENT Name (First, Initial?, Last)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Initial (#PCDATA)>
<!ELEMENT Last (#PCDATA)>
<!ELEMENT Phone (Country, Area, Local)>


<!ELEMENT Corp (CorpName, Addr, CorpPhone+)>
<!ATTLIST Corp Id CDATA #REQUIRED>
<!ELEMENT CorpName (#PCDATA)>
<!ELEMENT CorpPhone (Country, Area, Local, Name, Title)>
<!ELEMENT Title (#PCDATA)>

<!ELEMENT Area (#PCDATA)>
<!ELEMENT Local (#PCDATA)>

<!ELEMENT Addr (Unit?, Num, Street, City, Prov, Country, Postal)>
<!ELEMENT Unit (#PCDATA)>
<!ELEMENT Num (#PCDATA)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Prov (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT Postal (#PCDATA)>

=== lee0nerd0/XML-DTD/owner.xml
<!DOCTYPE Owner SYSTEM "owner.dtd">


<Owner>
	<Indiv Id="MD">
		<Name>
			<First>Man</First>
			<Initial>J</Initial>
			<Last>Dem</Last>
		</Name>
		<Addr>
			<Unit>4</Unit>
			<Num>33</Num>
			<Street>Marble</Street>
			<City>Kensington</City>
			<Prov>Ontario</Prov>
			<Country>Canada</Country>
			<Postal>M6Y2N6</Postal>
		</Addr>
		<Phone>
			<Country>1</Country>
			<Area>416</Area>
			<Local>9871234</Local>
		</Phone>
	</Indiv>
		
	<Corp Id="SS">
		<CorpName>Son and Sons</CorpName>
		<Addr>
			<Num>55</Num>
			<Street>Knoxville</Street>
			<City>Lampton</City>
			<Prov>Ontario</Prov>
			<Country>Canada</Country>
			<Postal>N8Y3N6</Postal>
		</Addr>
		<CorpPhone>
			<Country>1</Country>
			<Area>647</Area>
			<Local>5671234</Local>
			<Name>
				<First>Jet</First>
				<Initial>P</Initial>
				<Last>Son</Last>
			</Name>
			<Title>CEO</Title>
		</CorpPhone>
	</Corp>


</Owner>
