=== lee0nerd0/XML-DTD/renter.dtd
<!ELEMENT Renter (Tenant*)>
<!ELEMENT Tenant (Name, Phone*, Properties)>
<!ATTLIST Tenant Id ID #REQUIRED>
<!ELEMENT Name (First, Initial?, Last)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Initial (#PCDATA)>
<!ELEMENT Last (#PCDATA)>

<!ELEMENT Phone (Country, Area, Local)>
<!ATTLIST Phone Type (Cell|Home|Work|Other) #REQUIRED>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT Area (#PCDATA)>
<!ELEMENT Local (#PCDATA)>

<!ELEMENT Properties (Property*)>
<!ELEMENT Property EMPTY>
<!ATTLIST Property Id CDATA #REQUIRED>

=== lee0nerd0/XML-DTD/renter.xml
<!DOCTYPE Renter SYSTEM "renter.dtd">


<Renter>

	<Tenant Id="JS">
		<Name>
			<First>Joe</First>
			<Last>Schmoe</Last>
		</Name>
		<Phone Type="Home">
			<Country>1</Country>
			<Area>416</Area>
			<Local>5555555</Local>
		</Phone>
		<Properties>
			<Property Id="MC001"/>
		</Properties>
	</Tenant>

	<Tenant Id="JD">
		<Name>
			<First>Jane</First>
			<Last>Doe</Last>
		</Name>
		<Phone Type="Work">
			<Country>1</Country>
			<Area>647</Area>
			<Local>8888888</Local>
		</Phone>
		<Properties>
			<Property Id="UR001"/>
		</Properties>
	</Tenant>
	
</Renter>
